name: personal_finance
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  xml: ^6.3.0


  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

 